version: '3'

services:

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: unless-stopped
    container_name: flask-template
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
    networks:
      - npm-network

networks:
  npm-network:
   external: true